from . import otm_store
from . import otm_store_location
from . import product_template
from . import otm_product_batch
from . import otm_stock_move
from . import otm_stock_quant
from . import otm_purchase
from . import otm_stock_receipt
from . import otm_stock_transfer
from . import otm_stock_issue
from . import otm_stock_return
from . import otm_stock_adjustment
from . import otm_dashboard
